language: php

sudo: false

env:
  global:
    - secure: "VlhsC2uoUHIDXmcCihkByD5s3YjdaVPcLFA8xjbiNsGTLWn+BSn/0Az6QAVPwxs4c/osY8wvHcV7uyhEe4S2Am1IdUv5YxqtjjjVE25Sif0HY+mSrT1fC10I+Zp/rnnQwImGW0KfRjqgnIov+0+k7znxHOQYOYv+O+yXQdUL5uSXvE/ZNVs7c6AKThggPlnKjvEN4rYDPINxMblFAjcTk2y7ZJ3EBuA7QRguLjfJ9sCJICyM8PWKqJwH8SYNTK2zH5dM2M5433nWJZVaeyn39k1s+kzdErRrHaU9MPMFdQzCYLAk+1sbK+sj8CYaJoo7A5XqKDG0lEF+YXKSzf3unBD6u4y03TotfzgbBmNdMSswldEzrZuKTfEw3NmqakrNcza+xSm366q9oF8s71kfmT5clsRjXy4e11QIIfuJSmG7DRl/6kemEFVMX3eUhVYEu0rURGYUxZhOoAUWMN/soGcXbGHKiU7+aNSgfM9y96jHiRJFLvmvS1EMq3tu46pqiDjqLJb2aW3ZG6wvXUc86TCj6qW3pabQUXo5uYBDUXQ3uhZ4/ZpN8E+FcoQ+L7rnVEiZ6ibkANcPFlxr0Cbn6mSmlYtEWNb+/4KK/nG+hX27zpJNmi0puTra+6VO19dzucz84ZLkt33AkwZtVis7n1KfYG9IWjhAE5fzfyWuh3Y="
    - secure: "Fp4k6WKbwPUQIoY5bB69Drgg4i+1zaRADceJrKrLhga3JPsz27mFd1ejZ6RAS0KhRlCMMHyNMF/rq4XxM/cnEdtxH5S5hiKqpg5eNIPsc/kUruN69a8v2PxRTNK7d+cMrJci2YUPSl+reYG1DwC49qLXV1ilpX4Xehzd/BGxIaUOliC5KWL2a8gLgeBXx3XtB1lOZqsEdTta3JiM8DPm2eltTwtI3dgLbk7uf0ZvkYJor8cY7O6wHQItN7euXtCPYo5qN1TcD4fKOtTbYMfe/1JnxDOkt5OsQzWaiysIBSwxdJwtAaBJ+CmPQI29X27jCvvuRysP/xLthcLkEauy/RjUPHxYKeMK/tGFMPxONmxLs1Av+8hysw9pc+KR/ggwWlx+dQLhZS5XEDic6tCRNQZQNe3qEpRpQkOkDLPBWlFqsvVs4bXPpuq64j6Ojj1+03sjimK2Vz17mMES/CpOMwhPY2Bk4zKP0ceH6JatMlJhgm7vxICkoeCWpuLXfwzKBO4CuDq6f34BLUvTKP1YunnsYyjnxLoVz9Njckb4gjKE22fNHPU7qOsZ++bQJJjubJkC/V/KhLVooGRZxORVRFHJYzJJXPDTrwgX8sHNSLCuK+jMvtICBKXhpDPoOafWjzIvIKVhaLDARIpgvj9zSOEI5gFmXCQYj/HMNxSwK2U="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: WITH_CS=true
    - php: 5.6
      env: WITH_COVERAGE=true
    - php: 7
    - php: hhvm
  allow_failures:
    - php: 7
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then IS_MERGE_TO_MASTER=true; else IS_MERGE_TO_MASTER=false; fi
  - if [[ "$WITH_COVERAGE" != "true" && "$IS_MERGE_TO_MASTER" == "false" && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer validate
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - composer install --prefer-dist

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - mkdir -p build/logs

script:
  - if [[ "$WITH_COVERAGE" == "true" && "$IS_MERGE_TO_MASTER" == "true" ]]; then vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --configuration=test/Unit/phpunit.xml; fi
  - if [[ "$WITH_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run; fi

after_success:
  - if [[ "$WITH_COVERAGE" == "true" && "$IS_MERGE_TO_MASTER" == "true" ]]; then vendor/bin/test-reporter --coverage-report=build/logs/clover.xml; fi

notifications:
  email: false
